version: "3.5"

services:
  nginx:
    image: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    hostname: ${HOSTNAME}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /letsencrypt/html:/tmp/letsencrypt
    ports:
      - 80:80
  letsencrypt:
    image: kvaps/letsencrypt-webroot
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt:/etc/letsencrypt
      - /letsencrypt/html:/tmp/letsencrypt
    environment:
      - DOMAINS=${HOSTNAME}
      - EMAIL=${EMAIL}
      - WEBROOT_PATH=/tmp/letsencrypt
      - STAGING=0
